crash-utility/arm64: assign page_offset with kernel configure value
On RHEL9, crash hits a bug when executing "crash /proc/kcore" : seek
error: kernel virtual address: ffff6a0f3fff0000 type: "pmd page"

The kernel virtual address does not vary with va_actual bits, instead,
is determined by configuration value. But crash does not observe this
fact.

Since vabits_actual related kernel commit is introduced after arm64 mm
layout flip commit, so changes are safe under the condition if
(ms->VA_BITS_ACTUAL), and keep else branch untouched.

Signed-off-by: Pingfan Liu <piliu@redhat.com>
Cc: HAGIO KAZUHITO <k-hagio-ab@nec.com>
Cc: Lianbo Jiang <lijiang@redhat.com>
Cc: Bhupesh Sharma <bhupesh.sharma@linaro.org>
To: crash-utility@redhat.com